### ISSUE TITLE
The icon is hidden, but the mouse pointer still reacts with it.

### ISSUE THREAD

**Issue by gamer4eg** [Eternita-S/QuestAWAY#1]
![image](https://user-images.githubusercontent.com/23147230/132625660-c8d83b52-41e5-4015-ad01-f1dd94100dc0.png)

**Comment by Serfrost** [comment]
I can confirm this is still an issue and prevents being able to click on Aetherytes to teleport.

**Comment by Limiana** [comment]
Unfortunately there isn't much possibility to hide them absolutely completely, the only way this could be dealt with is by finding a function that is responsible for redrawing icons and modifying it, but such function is unknown to me at this moment.

**Comment by Serfrost** [comment]
Just a note for any readers: You can hold CTRL to bring Aetherytes to the top in order to click them.  It's a workaround, but it works for the time being.
