### ISSUE TITLE
New update

### ISSUE THREAD

**Issue by serwiibox** [Eternita-S/QuestAWAY#12]
Hi, iwas wondering if we are gonna get a new update for this plugin. It makes the game more cleaner.

**Comment by jtabox** [comment]
There is an update available, but for some reason if you had the plugin installed already, the new update won't show up in Dalamud Plugin Installer. You need to delete it, restart game and reinstall.
I had that issue, had the previous version installed and it kept showing as not updated (got the warning with red letters that the plugin isn't updated and I should wait for the dev to update). Only today did it occur to me to check here and see what's going on, and saw there's an update but I wouldn't get it. So I deleted the previous version, restarted the game and the new version was now available for install.
