### ISSUE TITLE
Please Update to Endwalker

### ISSUE THREAD

**Issue by kgetit** [Eternita-S/QuestAWAY#2]
As title states. Love this addon!

**Comment by Limiana** [comment]
Hello, it's updated and available through Dalamud's main repo with testing mode enabled. Enable testing mode here: 
![image](https://user-images.githubusercontent.com/5073202/145676642-9e56e7d4-f02d-4032-b96c-8d51831fc01b.png)

**Comment by kgetit** [comment]
OH NICE! Thank you very much!!
