### ISSUE TITLE
Minimap icons are not being hidden after the 7.1 update

### ISSUE THREAD

**Issue by Ennea** [Eternita-S/QuestAWAY#23]
As the title says. The big map icons are properly being hidden when enabling that option, but minimap icons are not.

**Comment by Limiana** [comment]
Oops, I forgot to even look at minimap

**Comment by BigBrainAFK** [comment]
This can be closed now as its fixed (in my own testing) right?

**Comment by Ennea** [comment]
Oh yea, I can just do that as the issue author as well.
